// src/app/(auth)/pair.tsx
// RecallAR — Patient device pairing screen
//
// PLACEHOLDER: This screen will scan a QR code generated by the caregiver
// app and exchange it for a long-lived patient session via
// AuthService.pairDevice(pairingToken) — to be implemented alongside the
// DevicePairing table and service.
//
// Once paired, the session is persisted and this screen is never shown
// again on this device — the root layout routes paired devices straight
// to (patient)/index.tsx.
//
// Dependency (when implementing the scanner):
//   npx expo install expo-camera

import { StyleSheet, Text, View } from 'react-native';

export default function PairDeviceScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Set up this device</Text>
      <Text style={styles.body}>
        Ask the patient's caregiver to open RecallAR on their phone, go to{' '}
        <Text style={styles.bold}>Manage Patient → Pair Device</Text>, and
        show the QR code on this screen.
      </Text>

      <View style={styles.scannerPlaceholder}>
        <Text style={styles.placeholderText}>Camera scanner goes here</Text>
      </View>

      <Text style={styles.hint}>
        This step only needs to be done once per device.
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 12,
    textAlign: 'center',
  },
  body: {
    fontSize: 16,
    color: '#4B5563',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 32,
  },
  bold: {
    fontWeight: '700',
    color: '#111827',
  },
  scannerPlaceholder: {
    width: '100%',
    aspectRatio: 1,
    maxWidth: 320,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    marginBottom: 24,
  },
  placeholderText: {
    color: '#9CA3AF',
    fontSize: 14,
  },
  hint: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
  },
});